# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Sample Posts',       url: 'sample-posts'}
- {name: 'Documentation',      url: 'documentation'}
- {name: 'About',              url: 'about'}
- {name: 'Contact',            url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link:    'https://twitter.com/AlexZahnAudio'}
- {icon: 'instagram', link:  'https://www.instagram.com/alexzahnaudio/'}
- {icon: 'github', link:     'https://github.com/alexzahnaudio'}
- {icon: 'gamepad', link:    'https://rocketsciencewins.itch.io/'}
- {icon: 'envelope', link:   'mailto:alex@alexzahnaudio.com'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
